# docker-compose.yml
# Para rodar o backend Node.js localmente em container

version: '3.8'

services:
  # Servidor API (Node.js + Express)
  api:
    container_name: qiabaco-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
